# ============================================
# QUARKUS CONFIG (DEV)
# ============================================
quarkus:
  http:
    #host: 192.168.1.77
    host: localhost
    port: 8080

  datasource:
    jdbc:
      url: jdbc:h2:./db/kcsd;MODE=MySQL

  hibernate-orm:
    packages: kz.kase.example.model
    schema-management:
      # Accepted values: none, create, drop-and-create, drop, update, validate.
      strategy: drop-and-create
      # strategy: validate
    log:
      sql: true
      format-sql: false
      highlight-sql: false
      jdbc-warnings: true  

  log:
    level: INFO
    min-level: TRACE
    
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"
      
    file:
      path: log/trace.log
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"
      enabled: true
      
    category:
      kz.kase.example:
        level: TRACE

  swagger-ui:                                                                                                                                                                                                                                   
    always-include: true